---

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev
namePrefix: dev-

resources:
  - ../../base/

patches:
  - path: patch-deployment.yml

configMapGenerator:
  - name: custom-html-0
    files:
      - index.html